import Head from 'next/head';
import './globals.css';
import Footer from '../layout/Footer';
import Header from '../layout/Header';
import LayoutWrapper from '../layout/LayoutWrapper';
import Nav from '../layout/Nav';
import prisma from '../../../src/lib/prisma_client';
import { headers } from 'next/headers';
import SchoolNotFound from '../components/SchoolNotFound'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};


export default async function RootLayout({ children }) {

  const headersList = headers();
  const domain = headersList.get('host')

  const school_info = await prisma.websiteUi.findFirst({
    where: {
      school: {
        domain: domain
      }
    },
    select: {
      header_image: true
    }
  })

  return (
    school_info ?
      <html lang="en">
        <Head>
          <title>Home</title>
        </Head>
        <body>
          <LayoutWrapper>
            <Header header_image={school_info?.header_image} />
            <Nav serverhost={process.env.SERVER_HOST} />
            {children}
          </LayoutWrapper>
          <Footer />
        </body>
      </html>
      :
      <SchoolNotFound />
  );




}
