import Head from 'next/head';
import './globals.css';
import Footer from '../layout/Footer';
import Header from '../layout/Header';
import LayoutWrapper from '../layout/LayoutWrapper';
import Nav from '../layout/Nav';
import prisma from '../../../src/lib/prisma_client';
import { headers } from 'next/headers';
import SchoolNotFound from '../components/SchoolNotFound'
import React from 'react';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };


export default async function RootLayout({ children }) {

  const headersList = headers();
  const domain = headersList.get('host')

  const school_info = await prisma.websiteUi.findFirst({
    where: {
      school: {
        domain: domain
      }
    },
    select: {
      header_image: true,
      eiin_number: true,
      facebook_link: true,
      twitter_link: true,
      google_link: true,
      linkedin_link: true,
      youtube_link: true
    }
  })

  return (
    school_info ?
      <html lang="en">
        <Head>
          <title>Home</title>
        </Head>
        <body>
          <LayoutWrapper>
            <Header
              eiin_number={school_info?.eiin_number}
              header_image={`${process.env.SERVER_HOST}/api/get_file/${school_info?.header_image?.replace(/\\/g, '/')}`}
            />
            <Nav serverhost={`${process.env.SERVER_HOST}`} />
            <div onClick={console.log("hi....")}>
              {children}
            </div>
          </LayoutWrapper>
          <Footer
            facebook_link={school_info?.facebook_link || ''}
            twitter_link={school_info?.twitter_link || ''}
            google_link={school_info?.google_link || ''}
            linkedin_link={school_info?.linkedin_link || ''}
            youtube_link={school_info?.youtube_link || ''}
          />
        </body>
      </html>
      :
      <SchoolNotFound />
  );




}
